---
- hosts: dev
  become: True
  tasks:
    - name: Update the apt package index
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install packages for apt add repository over HTTPS
      become: yes
      apt:
        name: "{{ packagesdep }}"
        force_apt_get: yes
        state: latest
        update_cache: yes
      vars:
        packagesdep:
        - git
        - apt-transport-https
        - ca-certificates
        - wget
        - software-properties-common
        - gnupg2
        - curl

    - name: Add Apt signing key from official docker repo
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: add docker official repository for Debian Stretch
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present

    - name: Index new repo into the cache
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: actually install docker
      apt:
        name: "docker-ce"
        state: latest

#    - name: Install Docker Module for Python
#      pip:
#        name: docker
  
    - name: install python3-docker
      apt:
        name: python3-docker
        state: latest
      
    - name: Adding user USER  to docker group
      user:
        name: "admin"
        groups: "docker"
        append: "yes"
    
 #   - name: Log in
 #     docker_login:
 #       username: ayeliferov
 #       password: "{{ DOCKERHUB_TOKEN }}"
 #       reauthorize: yes

    - name: Start the container
      docker_container:
        name: petclinic
        image: "ayeliferov/epam_lab:FinalProject_{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
    
  #  - name: Log out of DockerHub
  #    docker_login:
  #      state: absent
  #      email: ayeliferov@gmail.com